Update the article
OpenBXI/bxibase pull request #5
Opened 2017-04-13 07:29 UTC by jnquintin

2017-04-13 12:46 UTC, vigneras approved these changes

2017-04-13 12:48 UTC, vigneras requested changes
Be consistent: either change struct foo_s_t everywhere or nowhere. One struct foo remains on the same line.
JN: I correct it in a following commit, I agree I should have done it in the same commit.

2017-04-13 12:50 UTC, vigneras approved these changes

2017-04-14 07:33 UTC, merged

2017-04-14 11:06 UTC, vigneras commented on misc/articles/hlpic/resources/Error Management.ipynb
> +    "In C if memory management can be seen as a powerfull tool, C error management is definitely the main reason of buggy C programs. Currently, errors in C are tradionnally based on integer (returne
The sentence you propose is not equivalent to the original one.

2017-04-14 11:06 UTC, vigneras commented on misc/articles/hlpic/resources/Error Management.ipynb
> +    "* very poor: a simple integer does not hold any context, it cannot tell a lot on the reason of an issue;\n",
I prefer the explicit 'because' here

2017-04-14 11:06 UTC, vigneras commented on misc/articles/hlpic/resources/Error Management.ipynb
> +    "Notice the output now provides much more informations: \n",
information is correct.

2017-04-14 11:06 UTC, vigneras commented on misc/articles/hlpic/resources/Error Management.ipynb
> +    "Of course, one might argue that the first example is not the be way of doing this. However the error interface suggested ease the error handling and reporting. In addition, if the error is not o
I prefer the orginal sentence.

2017-04-14 11:06 UTC, vigneras commented on misc/articles/hlpic/resources/String Manipulation.ipynb
> +    "String manipulation is usually a headache in C compared to Python, Perl or even Java which is compiled. One of the main reason is probaly the choice of the [NULL string terminator](https://en.wi
No, the ascii character is NUL, not NULL.

2017-04-14 11:06 UTC, vigneras commented on misc/articles/hlpic/resources/String Manipulation.ipynb
> +    "`bxistr_prefixer()` allows a string to be prefixed.\n",
No, I am talking about the set of all `bxistr_prefixer_*()` functions. Maybe, `bxistr_prefixer_*()` instead of `bxistr_prefixer*()` would make it clearer?

2017-04-14 11:17 UTC, trosh commented on misc/articles/hlpic/resources/Error Management.ipynb
> +    "In C if memory management can be seen as a powerfull tool, C error management is definitely the main reason of buggy C programs. Currently, errors in C are tradionnally based on integer (returne
> makes it at the same time very poor and very weak

What's the difference ?